const $=s=>document.querySelector(s);let current=null;
async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json'},...opt});if(!r.ok)throw new Error(await r.text());return r.json()}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function refreshList(){const items=await api('/api/incidents');$('#incidentList').innerHTML=items.map(i=>`<div class="incident-item ${current?.id===i.id?'active':''}" data-id="${i.id}">${esc(i.title)}<small>${i.id} · ${i.events.length} events</small></div>`).join('');document.querySelectorAll('.incident-item').forEach(x=>x.onclick=()=>load(x.dataset.id))}
async function load(id){current=await api('/api/incidents/'+id);showIncidents();render();refreshList()}
function showQA(){$('#qaView').classList.remove('hidden');$('#incidentView').classList.add('hidden');$('#qaTab').classList.add('active');$('#incidentTab').classList.remove('active')}
function showIncidents(){$('#qaView').classList.add('hidden');$('#incidentView').classList.remove('hidden');$('#qaTab').classList.remove('active');$('#incidentTab').classList.add('active')}
function render(){if(!current)return;$('#incidentId').textContent=current.id+' · '+current.status.toUpperCase();$('#title').textContent=current.title;$('#description').textContent=current.description||'No description';$('#status').textContent=current.status.toUpperCase();$('#eventCount').textContent=current.events.length;$('#proposalCount').textContent=current.proposals.length;const top=current.hypotheses?.[0];$('#confidence').textContent=top?Math.round(top.confidence*100)+'%':'—';$('#summary').textContent=current.summary||'Run analysis to generate an evidence-backed brief.';$('#hypotheses').innerHTML=(current.hypotheses||[]).map(h=>`<div class="hypo"><div class="row"><span class="cause">${esc(h.cause)}</span><span class="tag">${Math.round(h.confidence*100)}%</span></div><div class="bar"><i style="width:${h.confidence*100}%"></i></div><div class="muted">${esc(h.evidence)}</div></div>`).join('')||'<div class="muted">No hypotheses yet.</div>';$('#timelineCount').textContent=(current.timeline||[]).length+' events';$('#timeline').innerHTML=(current.timeline||[]).map(e=>`<div class="event"><time>${esc(e.timestamp||'')}</time><strong>${esc(e.source.toUpperCase())} · ${esc(e.service)}</strong><p>${esc(e.message)}</p></div>`).join('')||'<div class="muted">No timeline yet.</div>';$('#proposals').innerHTML=(current.proposals||[]).map((p,i)=>`<div class="proposal"><div class="row"><span class="cause">${esc(p.action)}</span><span class="tag">${p.status}</span></div><div class="muted">${esc(p.rationale)}</div><div class="muted"><b>Verification:</b> ${esc(p.verification)}</div>${p.status==='pending'?`<button onclick="approve(${i})">Human review</button>`:''}</div>`).join('')||'<div class="muted">No safe proposals yet.</div>'}
async function analyze(){if(!current)return;$('#analyzeBtn').disabled=true;$('#analyzeBtn').textContent='Agents collaborating…';try{current=await api(`/api/incidents/${current.id}/analyze`,{method:'POST'});render();refreshList()}catch(e){alert(e.message)}finally{$('#analyzeBtn').disabled=false;$('#analyzeBtn').textContent='Run Multi-Agent Analysis'}}
async function approve(i){try{current=await api(`/api/incidents/${current.id}/proposals/${i}/approve`,{method:'POST'});render()}catch(e){alert(e.message)}}
async function ask(){const question=$('#question').value.trim(),context=$('#context').value.trim();if(!question){alert('Enter a question first.');return}$('#askBtn').disabled=true;$('#askBtn').textContent='NexaRAG is reasoning…';$('#answer').className='answer muted';$('#answer').textContent='Gathering evidence and generating a grounded answer…';$('#sources').innerHTML='';try{const r=await api('/api/query',{method:'POST',body:JSON.stringify({question,context})});$('#answer').className='answer';$('#answer').textContent=r.answer||'No answer returned.';$('#answerMode').textContent=r.mode==='provided_data'?'ANSWERED FROM YOUR DATA':'ANSWERED FROM EXTERNAL SOURCES';$('#modeBadge').textContent=r.mode==='provided_data'?'DATA-FIRST':'WEB FALLBACK';if(r.sources?.length){$('#sources').innerHTML='<h3>Sources</h3>'+r.sources.map(s=>`<a class="source" href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.title)}</a>`).join('')}}catch(e){$('#answer').textContent='Request failed: '+e.message;$('#answerMode').textContent='ERROR'}finally{$('#askBtn').disabled=false;$('#askBtn').textContent='Ask NexaRAG'}}
$('#askBtn').onclick=ask;$('#clearBtn').onclick=()=>{$('#question').value='';$('#context').value='';$('#answer').textContent='Your grounded answer will appear here.';$('#answer').className='answer muted';$('#sources').innerHTML='';$('#answerMode').textContent='Waiting for a question';$('#modeBadge').textContent='DATA-FIRST'};$('#context').oninput=()=>$('#modeBadge').textContent=$('#context').value.trim()?'DATA-FIRST':'WEB FALLBACK';$('#qaTab').onclick=showQA;$('#incidentTab').onclick=()=>{showIncidents();if(current)render()};$('#analyzeBtn').onclick=analyze;$('#demoBtn').onclick=async()=>{current=await api('/api/demo/seed',{method:'POST'});showIncidents();render();refreshList()};$('#newBtn').onclick=async()=>{const title=prompt('Incident title');if(!title)return;const description=prompt('Short description')||'';current=await api('/api/incidents',{method:'POST',body:JSON.stringify({title,description})});showIncidents();render();refreshList()};$('#eventForm').onsubmit=async e=>{e.preventDefault();if(!current)return;await api(`/api/incidents/${current.id}/events`,{method:'POST',body:JSON.stringify({source_type:$('#source').value,service:$('#service').value,message:$('#message').value,severity:$('#severity').value})});$('#message').value='';await load(current.id)};refreshList();
